### PR TITLE
Added Quasar Play graphics

### PR DESCRIPTION
**Pull request by kasp1**
I thought it might be a good idea to keep the Play app's graphics in this repository. Feel free to scrap this pull request if you don't think so.

### CODE REVIEW

**Comment by zuck** [comment]
Good idea...Actually I was thinking to add Quasar Play app graphics too.

My concern was if we should create a new logo/icon for the app: a nice solution could be to replace the "black hole" in the middle of the quasar nebula with a "play arrow" instead (same color)...

**Comment by rstoenescu** [comment]
@zuck it's your call. merge it or work out the details between you two. Thanks!

**Comment by kasp1** [comment]
I honestly don't care as long as I can just take the dist files as they are (the filenames in dist/quasar-play and image dimensions should be kept) and drag & drop them to the app, it can be any graphics you guys wish to have in the app.

**Review by rstoenescu — APPROVED** [review]

**Comment by kasp1** [comment]
Note: the iOS icon and splash screen can't have transparency.

**Comment by zuck** [comment]
@kasp1 Could you please open a new PR using the new Quasar Play logo? You can find it at `dist/svg/quasar-play-logo[-inline].svg`

**Comment by kasp1** [comment]
The Play logo looks great! Good job. It's a bit of work remaking the splash screens and exporting everything including the icons. I might a look once I'm not overwhelmed with my own projects.

**Pull request merged**
